### ISSUE TITLE
NIRSSeries should specify data dimensions and dtype

### ISSUE THREAD

**Issue by rly** [agencyenterprise/ndx-nirs#32]
The class diagram for `NIRSSeries` says that `data` should have a numeric dtype and 2 dimensions (time x channels), but as far as I can tell, the schema https://github.com/agencyenterprise/ndx-nirs/blob/main/spec/ndx-nirs.extensions.yaml#L179-L186 specifies no such requirements. `NIRSSeries` extends `TimeSeries` and does not modify any properties of the "data" dataset.

To ensure that the data stored in a `NIRSSeries` meets the desired requirements, I recommend modifying the schema for `NIRSSeries` to define the "data" dataset explicitly as:
```yaml
  - name: data
    dtype: numeric
    dims:
    - num_times
    - num_channels
    shape:
    - null
    - null
    doc: Recorded NIRS data.
```
See https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.ecephys.yaml#L18-L42 and https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.ecephys.yaml#L131-L141 as examples.
